edge:
  cam_id: "pi5_cam_a"
  fps: 1.0
  emit_jsonl: "data/detections.jsonl"
  mqtt: null  # e.g., "mqtts://user:pass@host:8883/topic"
  web:
    enabled: true
    host: "0.0.0.0"
    port: 8080
    title: "pi5_cam_a live"
    jpeg_quality: 80

intuitus:
  enabled: true
  impl: "intuitus.roi_diff:DiffROI"
  keyframe_sec: 2.0
  min_blob_area: 300
  dilate: 11
  max_roi: 8
  max_area_frac: 0.4

quiddity:
  impl: "quiddity.yolo_ort:YOLOv8ORT"
  model_path: "models/yolov8n.onnx"
  img_size: 512
  conf_th: 0.35
  iou_th: 0.5
  classes_include: ["person", "car"]

haecceity:
  min_bbox_h_frac: 0.08
  min_sharpness: 25.0
  specialists:
    - impl: "haecceity.person_osnet:PersonOSNet025"
      model_path: "models/osnet_x0_25.onnx"
      crop: 192
    - impl: "haecceity.vehicle_signature:VehicleSignature"
      hist_bins: 32
  fallbacks:
    - impl: "haecceity.generic_osnet:GenericOSNet025"
      model_path: "models/osnet_x0_25.onnx"
      crop: 192
