edge:
  cam_id: "pi5_cam_a"
  fps: 1.0
  source: 0
  emit_jsonl: "data/stage1_tracks.jsonl"

quiddity:
  impl: "quiddity.yoloe_pt:YOLOEPT"
  model_name: "yolov8s"          # Ultralytics alias; auto-downloads on first run
  conf_th: 0.35
  classes_include: ["person"]
