edge:
  cam_id: "pi5_cam_a"
  fps: 1.0
  source: "picam"
  emit_jsonl: "data/detections.jsonl"
  mqtt: null  # e.g., "mqtts://user:pass@host:8883/topic"
  web:
    enabled: true
    host: "0.0.0.0"
    port: 8080
    title: "pi5_cam_a live"
    jpeg_quality: 80

intuitus:
  enabled: true
  impl: "intuitus.roi_diff:DiffROI"
  keyframe_sec: 2.0
  min_blob_area: 300
  dilate: 11
  max_roi: 8
  max_area_frac: 0.4

quiddity:
  impl: "quiddity.yoloe_pt:YOLOEPT"
  model_path: "models/yoloe.pt"
  model_url: "https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8s.pt"
  conf_th: 0.35
  min_box_area_frac: 0.002
  max_box_area_frac: 0.85
  classes_include: ["person", "car"]
  dedup:
    enabled: true
    iou_thr: 0.6

haecceity:
  embed_classes: []
  specialists: []
  fallbacks: []
